pythonProject2/practiceProject2/Login_app/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name='Login_app'

urlpatterns = [
  path('', views.index, name='index'),
  path('register/', views.register, name='register'),
]

pythonProject2/practiceProject2/practiceProject2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Login_app.urls')),
]

pythonProject2/practiceProject2/Login_app/models.py
from django.db import models
from django.contrib.auth.models import User # importing the User model for using authrization
                                            # we will use username, email, password from this Model
# Create your models here.

class UserInfo(models.Model): #                                                  # To extend the information for User model we are creating another model which will be one_to_one relation-ship with user model
    user = models.OneToOneField(User, on_delete=models.CASCADE,primary_key=True) # connect user model in one_To_one relationship
                                                                                 # And saying that, User model id willbe its ID
    facebook_id = models.URLField(blank=True)                                   # user can keep this field empty
    profile_pic= models.ImageField(upload_to='profile_pics', blank=True) # profile image will be uploaded to 'media/profile_pics' folder

    def __str__ (self):
        return self.user.username # accessing the user name from User model

pythonProject2/practiceProject2/Login_app/forms.py
from django import forms
from django.contrib.auth.models import User           # importing user model
from .models import UserInfo                          # UserInfo model import


class UserForm(forms.ModelForm):
    password= forms.CharField(widget= forms.PasswordInput())      # will help to make proper password field
    class Meta():
        model= User    # User model form
        fields = ('username', 'password', 'email' )               # not using other fields

class UserInfoForm(forms.ModelForm):
    class Meta():
        model= UserInfo                                           # UserInfo model
        fields = ('facebook_id', 'profile_pic')                   # not using User foreign key field

pythonProject2/practiceProject2/Login_app/views.py
from django.shortcuts import render
from .forms import UserForm, UserInfoForm

# Create your views here.

def index(req):
    dict={'Title': 'Index Page',}

    return render(req, 'Login_app/index.html', context=dict)

def register(req):
    dict={'Title': 'Register',}
    user= UserForm()        # UserForm Object
    userInfo=UserInfoForm() # UserInfoForm Object




    dict['user']=user
    dict['userInfo']=userInfo
    return render(req, 'Login_app/register.html', context=dict)

pythonProject2/practiceProject2/templates/Login_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ Title }}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
   {% block head %} {% endblock %}
</head>
<body>

<!--NavBar-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'Login_app:index' %}">Home</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'Login_app:register' %}">Register</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="">Musician Form</a>
        </li>
        </li>

      </ul>
    </div>
  </div>
</nav>
<!--NavBar End-->

<div class="container" style="padding-top:20px;"> {% block body %} {% endblock %} </div>
</body>
</html>

pythonProject2/practiceProject2/templates/Login_app/index.html
{% extends 'Login_app/base.html' %}

{% block head %} {% endblock %}

{% block body %}
<h3> Index Page </h3>


{% endblock %}

pythonProject2/practiceProject2/templates/Login_app/register.html
{% extends 'Login_app/base.html' %}
{% load static %}
{% block head %} {% endblock %}

{% block body %}
<h3> Register </h3>

<!-- enctype="multipart/form-data"  and CSRF_token must be added for image/file data insert -->
<form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{user.as_p}}
      {{userInfo.as_p}}
      <input type="submit" value="submit" name="submit">

</form>

{% endblock %}